

#database properties
spring.datasource.url=jdbc:postgresql://localhost:5432/devicesclientrestappdb
spring.datasource.username=postgres
spring.datasource.password=csd1993
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#server properties
server.port=50600


#rest service information
devicesapp.url = http://192.168.1.38:50500/devices/names?name=

